# Dockerfile.nginx
# Use official Nginx image. Use the "stable" tag for production
FROM nginx:stable

# Copy static files
COPY staticfiles /static/

# Copy nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]