version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume: