# Generated by Django 5.0.1 on 2024-01-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthdetails',
            name='sub',
            field=models.CharField(default=8675309, max_length=200),
            preserve_default=False,
        ),
    ]
