# Generated by Django 5.0.1 on 2024-01-15 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_userauthdetails_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthdetails',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userauthdetails',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
