# Generated by Django 5.0.1 on 2024-01-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0003_weeklycharprogress_create_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestCompletionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_id', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('data_link', models.CharField(max_length=256)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
